/***********************************************                         
  DO NOT MODIFY THE CONTENTS OF THIS FILE.                              
  This header file has been auto-generated by xmelab.                        
  This should be included in user'c C file to                        
  facilitate the calling of imported tasks and functions.                        
************************************************/                        

#include "svdpi.h" 

#ifdef __cplusplus                          
    extern "C" {                          
#endif 

typedef struct { 
	int _a0;
 	int _a1;
 	 double _a2;
 } aunit_0x4bff31f0__SVPacket;


extern int c_get_count (void * _a1);

extern int c_string_length (const char *_a1);

extern double c_multiply_real (double _a1, double _a2);

extern void * c_create_counter (int _a1);

extern void c_use_scope_api ();

extern int c_pure_fibonacci (int _a1);

extern void c_use_userdata ();

extern void c_call_sv_export (int _a1);

extern void c_fill_packet (aunit_0x4bff31f0__SVPacket *_a1, int _a2, double _a3);

extern void c_destroy_counter (void * _a1);

extern svBit c_check_even (int _a1);

extern int c_blocking_sort (const svOpenArrayHandle _a1);

extern double c_pure_power (double _a1, int _a2);

extern void c_increment (void * _a1);

extern void c_fill_array (const svOpenArrayHandle _a1);

extern void c_process_packet (aunit_0x4bff31f0__SVPacket *_a1);

extern void c_print_2d_array (const svOpenArrayHandle _a1);

extern int c_sum_array (const svOpenArrayHandle _a1);

extern void c_use_time_api ();

extern char c_to_upper (char _a1);

extern void c_reverse_array (const svOpenArrayHandle _a1);

extern void c_print_string (const char *_a1);

extern int c_add (int _a1, int _a2);

#ifdef __cplusplus                          
 }                          
#endif

